### ISSUE TITLE
Main menu corrupts if you open it during a loading screen

### ISSUE THREAD

**Issue by iClaimThisName** [phanxgames/AetherStory#91] opened 2020-08-05 19:09 UTC
**Describe the bug**
If you open the main menu at just the right time during a loading screen (like when changing maps) it corrupts the main menu, and when you close the main menu you get stuck on the loading screen.

**To Reproduce**
Steps to reproduce the behavior (NOTE: you might need to be in a party to reproduce this, unconfirmed):
1. Switch maps
2. To corrupt the main menu: During the loading screen, press ESC right before the loading screen ends (might take a few tries) NOTE: spamming ESC does not seem to be very effective.
3. To get stuck in the loading screen: Close the main menu after it corrupts

**Expected behavior**
Expected behavior is that the menu does not open during the loading screen.

**Screenshots**
![buggybugbug](https://user-images.githubusercontent.com/69261909/89453593-ca0dfa00-d75f-11ea-90a0-78f6edda3d8a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.3.338

**Additional context**
Note: Both Charles and I (iclaim) have been able to reproduce this when changing maps, but we have yet to reproduce it when using telepads, and when logging into the game.

**Comment by CharlesIV** [comment] 2020-08-05 19:14
***Related Stack***
>TypeError: Error #1009
	at entities.visual::Player/get map_id()
	at ui.controls.cellRenderers::CellPartyStatus/onChange()
	at ui.controls.cellRenderers::CellPartyStatus/setPlayerFromData()
	at ui.controls.cellRenderers::CellPartyStatus/setData()
	at pheathers.controlUtils::PheatherDataGridCellRenderer/commitData()
	at feathers.controls.renderers::BaseDefaultItemRenderer/draw()
	at pheathers.controlUtils::PheatherDataGridCellRenderer/draw()
	at feathers.core::FeathersControl/validate()
	at feathers.layout::HorizontalLayout/validateItems()
	at feathers.layout::HorizontalLayout/layout()
	at feathers.controls::LayoutGroup/draw()
	at feathers.controls.supportClasses::DataGridRowRenderer/draw()
	at feathers.core::FeathersControl/validate()
	at feathers.controls::LayoutGroup/validate()
	at feathers.controls.supportClasses::DataGridDataViewPort/validateRowRenderers()
	at feathers.controls.supportClasses::DataGridDataViewPort/draw()
	at feathers.core::FeathersControl/validate()
	at feathers.controls::Scroller/refreshViewPortBoundsForMeasurement()
	at feathers.controls::Scroller/refreshViewPort()
	at feathers.controls::Scroller/draw()
	at feathers.controls::DataGrid/draw()
	at pheathers.controls::DataGrid/draw()
	at feathers.core::FeathersControl/validate()
	at pheathers.controls::NineGrid/autoSizeIfNeeded()
	at pheathers.controls::NineGrid/draw()
	at feathers.core::FeathersControl/validate()
	at feathers.core::ValidationQueue/advanceTime()
	at starling.animation::Juggler/advanceTime()
	at starling.core::Starling/advanceTime()
	at starling.core::Starling/nextFrame()
	at starling.core::Starling/onEnterFrame()

**Comment by CharlesIV** [comment] 2020-08-05 19:30
Duplicate of issue #79. (More information provided here)

**Comment by CharlesIV** [comment] 2020-08-13 16:20
Unable to replicate, presumed Fixed 0.3.85+

**Closed by CharlesIV** 2020-08-13 16:20 UTC
Labels: Duplicate, Major bug
