### ISSUE TITLE
storage lag

### ISSUE THREAD

**Issue by jessespy2** [phanxgames/AetherStory#115] opened 2020-10-04 10:25 UTC
**Describe the bug**
the storage takes a few secconds to update i thought i deleted my item

**To Reproduce**
1. While interacting with bank
2. Click on deposit
3. Wait
4. See item appear 3 secs later

**Expected behavior**
items disapear for a few secconds making it feel like item is in limbo/deleted to new players

**Screenshots**

**Context:**
 - Character Name: adiviah
 - OS: windows 8
 - Patch Version: 0.3.94
 - Game Build: donno

**Additional context**
may misslead new players and panic them for a sec

**Comment by CharlesIV** [comment] 2020-10-16 04:10
Thank you for your report. This is most likely caused by your connection latency with the server. I will close this report and reopen if others also notice large delays between interactions.

**Closed by CharlesIV** 2020-10-16 04:10 UTC
Labels: Resolved
