### ISSUE TITLE
Attack animation attempts to start before cooldown is over

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#131] opened 2020-12-20 02:18 UTC
**Describe the bug**
If you attack before the cooldown is up, the animation still (kind of) plays

**To Reproduce**
1. Join a battle
2. Spam the attack button

**Expected behavior**
The animation not show until the cooldown is over. (Wait for confirmation from server to start animation?)

**Screenshots**
https://user-images.githubusercontent.com/24666944/102703648-94197000-423f-11eb-8948-9ace1b9702d0.mp4

**Context:**
 - Character Name: Charles
 - OS: Windows
 - Patch Version: 0.3.102
 - Game Build: 397

**Comment by phanxgames** [comment] 2020-12-24 08:07
This is a result of the idea of immediate feedback.  Basically, when you press a button on your client it will show you raising your sword, and then once the server says "yes go ahead and use your sword" it plays the attack animation.
The problem is the client should be aware of the cooldown as well, not just the server, so the client can prevent you from hitting the button early. Then this immediate feedback will be reserved for high latency environments and feel great.

**Comment by phanxgames** [comment] 2021-02-23 07:03
Fixed with cooldown redials added to battle buttons.

**Closed by phanxgames** 2021-02-23 07:03 UTC
Labels: QoL Bug, Subj: Battle
