### ISSUE TITLE
Player Manager Null Exception

### ISSUE THREAD

**Issue by CharlesIV** [phanxgames/AetherStory#44] opened 2020-05-07 19:59 UTC
ID: 3925

TypeError: Error #1009
	at Function/PlayerManager.as$2:anonymous()
	at PhanxEngine.utils.processes::WaitFrames/run()
	at PhanxEngine.managers::ProcessManager/update()
	at PhanxEngine.core.entities::BaseSpriteEntity/update()
	at Game/update()
	at PhanxEngine::RootGame/onEnterFrame()
	at starling.events::EventDispatcher/invokeEvent()
	at starling.events::EventDispatcher/dispatchEvent()
	at starling.display::DisplayObject/dispatchEvent()
	at starling.display::DisplayObjectContainer/broadcastEvent()
	at starling.display::Stage/advanceTime()
	at starling.core::Starling/advanceTime()
	at starling.core::Starling/nextFrame()
	at starling.core::Starling/onEnterFrame()

Occurred when interacting with event id: e122_9_36.
Player reported: "Logging in.  Unable to log in after multiple attempts.  Game crash occurs after clicking play character (character Lee)"

**Comment by phanxgames** [comment] 2020-05-07 20:52
Added a null check. This appears to be caused by another player disposing at the same time they were logging in.
Should be fixed?

**Closed** 2020-08-05 12:04 UTC
Labels: Major bug, Needs testing
